### ISSUE TITLE
Import/Export of Snapshots

### ISSUE THREAD

**Issue by obitech** [joroec/virsnap#10]
Would it be possible to import/export snapshots in `qcow2` or a compressed format? Could also think about encryption at this point.

**Comment by joroec** [comment]
I start with explaining my point of view regarding the export feature. What is the initial use case for VM snapshots like created via virsnap? Efficient incremental backups to prevent data loss because of human failure. Apart from this, you typically want to have some (off-site / off-main-HDD) backups to prevent data loss because of hardware (disk) failure. I am sure this was your original intention when opening this issue.

It would be possible to implement a command that gathers information about the disks that are attached to a VM and creates an archive (e.g. tar) with all the disk files and the VM's manifest. This might get bulky for large VM disks and periodic export jobs, especially in the case of off-site backups over some sort of (slower) network connections, since a periodic export must always copy the whole VM disk. A smarter solution including differential file transmissions (e.g. using the rsync algorithm) when a previous export of the VM exists seems to be preferable and good idea.

I tend not to implement encryption at this point, because it introduces far more complexity for differential file transmissions. For secure transmissions of VMs, you can use a regular SSL connection. If you really want to encrypt data at rest, you could also LUKS encrypt the VM itself...

**Comment by joroec** [comment]
A first version of an export command is going to be merged to master in [this pull request](https://github.com/joroec/virsnap/pull/14).

**Comment by obitech** [comment]
Closed by #14
